name: Dependent Jobs

on: push

jobs:
  job_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: data
  job_on_windows:
    name: A Windows Job
    runs-on: windows-latest
    steps:
      - name: First step in windows job
        run: date
  job_on_macos:
    needs: [job_on_ubuntu, job_on_windows]
    name: A job that runs on Mac OS
    runs-on: macos-latest
  Final_job:
    needs: job_on_macos
    name: A final job
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello World!
